/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.5.1/samples
 */

plugins {
  application
}

repositories {
  mavenCentral()
}

dependencies {
  testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
  // Adding commons-lang3 dependency
  implementation("org.apache.commons:commons-lang3:3.12.0")
  testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

application {
  mainClass.set("com.gradlehero.themepark.RideStatusService")
}

// tasks.named<JavaCompile>("compileJava") {
//   options.isVerbose = true
// }

tasks.withType<JavaCompile> {
  options.isVerbose = true
}

tasks.named<Copy>("processResources") {
  include("**/*.txt")
}

// Java Plugin が自動で作成した jar タスクに対して、後から設定を追加している
tasks.named<Jar>("jar") {
  // アプリのエントリーポイントとなるクラスを指定している
  manifest {
    attributes["Main-Class"] = "com.gradlehero.themepark.RideStatusService"
  }
  // Jarファイルの名前を設定
  archiveFileName.set("test.jar")
}

// tasks.named<Test>("test") {
//   useJUnitPlatform()
// }

// JUnit Platform(JUnit 5)を使ってテストを実行してね
tasks.withType<Test>().configureEach {
  useJUnitPlatform()
  include("**/RideStatusServiceFailureTest.class")
}

tasks.register<JavaExec>("runJar") {
  classpath(tasks.named<Jar>("jar").map { it.archiveFile })
  // 実行時に必要なライブラリも参照する
  classpath(configurations.runtimeClasspath)
  args("teacups")
  mainClass.set("com.gradlehero.themepark.RideStatusService")
}

testing {
  suites {
    val test by getting(JvmTestSuite::class) {
      useJUnitJupiter()
    }
    register<JvmTestSuite>("integrationTest") {
      dependencies {
        implementation(project())
      }
    }
  }
}

tasks.named("check") {
  dependsOn(tasks.named("integrationTest"))
}
