/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.5.1/samples
 */

plugins {
  application
}

repositories {
  mavenCentral()
}

dependencies {
  testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

application {
  mainClass.set("com.gradlehero.themepark.RideStatusService")
}

// tasks.named<JavaCompile>("compileJava") {
//   options.isVerbose = true
// }

tasks.withType<JavaCompile> {
  options.isVerbose = true
}

tasks.named<Copy>("processResources") {
  include("**/*.txt")
}

// Java Plugin が自動で作成した jar タスクに対して、後から設定を追加している
tasks.named<Jar>("jar") {
  // アプリのエントリーポイントとなるクラスを指定している
  manifest {
    attributes["Main-Class"] = "com.gradlehero.themepark.RideStatusService"
  }
  // Jarファイルの名前を設定
  archiveFileName.set("test.jar")
}

tasks.named<Test>("test") {
  useJUnitPlatform()
}
