/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.5.1/samples
 */

plugins {
  application
  `java-library`
  `maven-publish`
}

group = "com.gradlehero"
version = "1.0-SNAPSHOT"

// プロジェクト全体のJava設定
// compileJava compileTestJava test runなどのJava関連タスクがJava17を使うようになる
java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}

repositories {
  mavenCentral()
}

dependencies {
  testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
  // Adding commons-lang3 dependency
  implementation("org.apache.commons:commons-lang3:3.12.0")
  implementation("com.fasterxml.jackson.core:jackson-databind:2.13.0")
  api("com.fasterxml.jackson.core:jackson-databind:2.13.0")
testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
  testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

application {
  mainClass.set("com.gradlehero.themepark.RideStatusService")
}

// tasks.named<JavaCompile>("compileJava") {
//   options.isVerbose = true
// }

tasks.withType<JavaCompile> {
  options.isVerbose = true
}

tasks.named<Copy>("processResources") {
  include("**/*.txt")
}

// Java Plugin が自動で作成した jar タスクに対して、後から設定を追加している
tasks.named<Jar>("jar") {
  // アプリのエントリーポイントとなるクラスを指定している
  manifest {
    attributes["Main-Class"] = "com.gradlehero.themepark.RideStatusService"
  }
  // Jarファイルの名前を設定
  archiveFileName.set("test.jar")
}

// tasks.named<Test>("test") {
//   useJUnitPlatform()
// }

// JUnit Platform(JUnit 5)を使ってテストを実行してね
tasks.withType<Test>().configureEach {
  useJUnitPlatform()
  include("**/RideStatusServiceFailureTest.class")
}

tasks.register<JavaExec>("runJar") {
  classpath(tasks.named<Jar>("jar").map { it.archiveFile })
  // 実行時に必要なライブラリも参照する
  classpath(configurations.runtimeClasspath)
  args("teacups")
  mainClass.set("com.gradlehero.themepark.RideStatusService")
}

testing {
  suites {
    val test by getting(JvmTestSuite::class) {
      useJUnitJupiter()
    }
    register<JvmTestSuite>("integrationTest") {
      dependencies {
        implementation(project())
      }
    }
  }
}

tasks.named("check") {
  dependsOn(tasks.named("integrationTest"))
}

// runとrunJarタスクのJavaバージョンを更新
tasks.withType<JavaExec>().configureEach {
  javaLauncher.set(javaToolchains.launcherFor {
    languageVersion.set(JavaLanguageVersion.of(17))
  })
}

publishing {
  publications {
    create<MavenPublication>("maven") {
      from(components["java"])
    }
  }
  repositories {
    maven {
      url = uri("<your-repository-url>")
      credentials {
        // ./gradlew publish -PmavenUsername=aws -PmavenPassword=<password>
        username = property("mavenUsername").toString()
        password = property("mavenPassword").toString()
      }
    }
  }
}

// ./gradlew print -PmyPropName=myPropValue
// tasks.register("print") {
//   doLast {
//     print(project.property("myPropName"))
//   }
// }

tasks.register("print") {
  doLast {
    println(project.findProperty("myPropName") ?: "defaultValue")

    if (project.hasProperty("myPropName1")) {
      println("Doing some conditional build logic")
    }
  }
}
