/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.5.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "theme-park-rides-status"

plugins {
  // Gradleが必要なJDKを自動ダウンロードできるようにするプラグイン
  // Gradle全体の設定なのでsettings.gradle.ktsに記載しておく
  id("org.gradle.toolchains.foojay-resolver-convention") version("0.4.0")
}
